### PR TITLE
fix Pagination-Total-Pages response header

### LINKED ISSUE #20: Invalid "Pagination-Total-Pages" in response headers
Hi @fabienpiette !

It seems like there's an issue with the way the "Pagination-Total-Pages" is computed.

When I have exactly the right amount of records to fill the last page, the "Pagination-Total-Pages" returned in the response headers is too high by 1.

For example :
- With 2 records and `page[size]=1` in the query, I get `"Pagination-Total-Pages"=>3` instead of 2 ;
- With 2 records and `page[size]=2` in the query, I get `"Pagination-Total-Pages"=>2` instead of 1 ;
- With 20 records and `page[size]=2` in the query, I get `"Pagination-Total-Pages"=>11` instead of 10 ;

I hope I've been clear.
Cheers!

### PR DESCRIPTION
**Pull request by Tao-Galasse**
This should fix #20 :)

### CODE REVIEW

**Comment by Tao-Galasse** [comment]
Found the issue: 
`(1/3).ceil => 0`
`(1.0/3.0).ceil => 1`
If we use floats instead of integers, we don't need the `+ 1` which caused the original issue in #20 
(example: `1 + (6/3).ceil => 3` instead of 2)

The only special case here is when count == 0 :
The current behaviour is `1 + (0/x).ceil => 1` ; with this fix, it would be `(0.0/x.0).ceil => 0` 
I don't know what's better when there is no record; Is there one empty page or no page ?

Depending your thoughts about it, I could add a condition for this special case.

**Comment by pauldub** [comment]
@fabienpiette what's you opinion on this? I'd rather maintain backward compatibility.

**Comment by fabienpiette** [comment]
> @fabienpiette what's you opinion on this? I'd rather maintain backward compatibility.

I think we can apply the fix with a breaking change in a new version (v0.4), what do you think about it?

**Comment by pauldub** [comment]
LGTM

**Pull request merged**
